In [8]:
from feature_engineering import *
df = pd.read_csv('./transformed.csv', index_col=0)
feature_engineering(df) 

#df_new = df.loc[:1000, df.columns!='Sales']

[autoreload of feature_engineering failed: Traceback (most recent call last):
  File "/Users/elenastein/opt/anaconda3/envs/dkb_env/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/Users/elenastein/opt/anaconda3/envs/dkb_env/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 394, in superreload
    module = reload(module)
  File "/Users/elenastein/opt/anaconda3/envs/dkb_env/lib/python3.6/imp.py", line 315, in reload
    return importlib.reload(module)
  File "/Users/elenastein/opt/anaconda3/envs/dkb_env/lib/python3.6/importlib/__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/elenastein/DSR/m_comp/feature_engineering.py", line 82
    OH_df_cols = pd.DataFrame(OH_encoder.transform(df[cat_col]))
             ^
IndentationError: expected an indented block
]

creating conversion table

/Users/elenastein/DSR/m_comp/feature_engineering.py:20: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  conversion = creating_conversion_table()
/Users/elenastein/DSR/m_comp/feature_engineering.py:25: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  df = creating_df_with_sorted_id(conversion)

reshuffle the data
Splitting X and y

,Store,Sales,Customers,Open,Promo,SchoolHoliday,year,month,week,day,...,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval,sorted id
0,353.0,3139.0,820.0,1,0.0,1.0,2013,1,1,1,...,b,b,900.0,7.0,2009.0,1,14.0,2013.0,"Feb,May,Aug,Nov",268
1,353.0,2686.0,835.0,1,0.0,1.0,2013,1,1,2,...,b,b,900.0,7.0,2009.0,1,14.0,2013.0,"Feb,May,Aug,Nov",268
2,353.0,2628.0,815.0,1,0.0,1.0,2013,1,1,3,...,b,b,900.0,7.0,2009.0,1,14.0,2013.0,"Feb,May,Aug,Nov",268
3,353.0,2677.0,856.0,1,0.0,1.0,2013,1,1,4,...,b,b,900.0,7.0,2009.0,1,14.0,2013.0,"Feb,May,Aug,Nov",268
4,353.0,2224.0,719.0,1,0.0,0.0,2013,1,1,5,...,b,b,900.0,7.0,2009.0,1,14.0,2013.0,"Feb,May,Aug,Nov",268
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
497371,1081.0,4974.0,836.0,1,0.0,0.0,2014,7,30,27,...,b,a,400.0,3.0,2006.0,0,0.0,0.0,None,455
497372,1081.0,7900.0,1123.0,1,1.0,1.0,2014,7,31,28,...,b,a,400.0,3.0,2006.0,0,0.0,0.0,None,455
497373,1081.0,7563.0,1198.0,1,1.0,1.0,2014,7,31,29,...,b,a,400.0,3.0,2006.0,0,0.0,0.0,None,455
497374,1081.0,6514.0,1021.0,1,1.0,1.0,2014,7,31,30,...,b,a,400.0,3.0,2006.0,0,0.0,0.0,None,455
497375,1081.0,6895.0,1045.0,1,1.0,1.0,2014,7,31,31,...,b,a,400.0,3.0,2006.0,0,0.0,0.0,None,455

In [ ]:
df_new = df.loc[:1000]

feature_engineering(df_new, test=True)

/Users/elenastein/DSR/m_comp/feature_engineering.py:25: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  df = creating_df_with_sorted_id(conversion)

Splitting X and y
         Store  Customers  Open  Promo  SchoolHoliday  year  month  week  day  \
0        353.0      820.0     1    0.0            1.0  2013      1     1    1
1        353.0      835.0     1    0.0            1.0  2013      1     1    2
2        353.0      815.0     1    0.0            1.0  2013      1     1    3
3        353.0      856.0     1    0.0            1.0  2013      1     1    4
4        353.0      719.0     1    0.0            0.0  2013      1     1    5
...        ...        ...   ...    ...            ...   ...    ...   ...  ...
497371  1081.0      836.0     1    0.0            0.0  2014      7    30   27
497372  1081.0     1123.0     1    1.0            1.0  2014      7    31   28
497373  1081.0     1198.0     1    1.0            1.0  2014      7    31   29
497374  1081.0     1021.0     1    1.0            1.0  2014      7    31   30
497375  1081.0     1045.0     1    1.0            1.0  2014      7    31   31

        day_week  ...  StoreType  Assortment CompetitionDistance  \
0              1  ...          b           b               900.0
1              2  ...          b           b               900.0
2              3  ...          b           b               900.0
3              4  ...          b           b               900.0
4              5  ...          b           b               900.0
...          ...  ...        ...         ...                 ...
497371         6  ...          b           a               400.0
497372         0  ...          b           a               400.0
497373         1  ...          b           a               400.0
497374         2  ...          b           a               400.0
497375         3  ...          b           a               400.0

        CompetitionOpenSinceMonth CompetitionOpenSinceYear Promo2  \
0                             7.0                   2009.0      1
1                             7.0                   2009.0      1
2                             7.0                   2009.0      1
3                             7.0                   2009.0      1
4                             7.0                   2009.0      1
...                           ...                      ...    ...
497371                        3.0                   2006.0      0
497372                        3.0                   2006.0      0
497373                        3.0                   2006.0      0
497374                        3.0                   2006.0      0
497375                        3.0                   2006.0      0

        Promo2SinceWeek  Promo2SinceYear    PromoInterval  \
0                  14.0           2013.0  Feb,May,Aug,Nov
1                  14.0           2013.0  Feb,May,Aug,Nov
2                  14.0           2013.0  Feb,May,Aug,Nov
3                  14.0           2013.0  Feb,May,Aug,Nov
4                  14.0           2013.0  Feb,May,Aug,Nov
...                 ...              ...              ...
497371              0.0              0.0             None
497372              0.0              0.0             None
497373              0.0              0.0             None
497374              0.0              0.0             None
497375              0.0              0.0             None

                                       sorted id
0        new id    268
Name: 353.0, dtype: int64
1        new id    268
Name: 353.0, dtype: int64
2        new id    268
Name: 353.0, dtype: int64
3        new id    268
Name: 353.0, dtype: int64
4        new id    268
Name: 353.0, dtype: int64
...                                          ...
497371  new id    455
Name: 1081.0, dtype: int64
497372  new id    455
Name: 1081.0, dtype: int64
497373  new id    455
Name: 1081.0, dtype: int64
497374  new id    455
Name: 1081.0, dtype: int64
497375  new id    455
Name: 1081.0, dtype: int64

[497376 rows x 24 columns]
   Store  Customers  Open  Promo  SchoolHoliday  year  month  week  day  \
0  353.0      820.0     1    0.0            1.0  2013      1     1    1
1  353.0      835.0     1    0.0            1.0  2013      1     1    2
2  353.0      815.0     1    0.0            1.0  2013      1     1    3
3  353.0      856.0     1    0.0            1.0  2013      1     1    4
4  353.0      719.0     1    0.0            0.0  2013      1     1    5

   day_week  ...    5    6    7    8    9   10   11   12   13   14
0         1  ...  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0
1         2  ...  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0
2         3  ...  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0
3         4  ...  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0
4         5  ...  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0

[5 rows x 35 columns]

In [ ]:
df.columns

In [ ]:
cat_col = [col for col in df.columns if df[col] in list(['StoreType', 'Assortment', 'PromoInterval'])]

In [ ]:
cat_col

In [ ]:
cat_col.append("sorted id")

In [ ]:
cat_col

In [ ]:
cat_col.remove("sorted id")

In [ ]:
cat_col

In [ ]:
X_